### ISSUE TITLE
Unable to use in client side rendering

### ISSUE THREAD

**Issue by ernoaapa** [Charmatzis/react-leaflet-google#1]
Hi,
have you used this in single page app what renders the map on client side?

On the second time when I render the map (for instance visiting in other page and coming back), I get following error and the map tiles don't show up at all:
<img width="963" alt="screen shot 2016-08-21 at 11 34 51" src="https://cloud.githubusercontent.com/assets/662535/17836239/563c3d7a-6793-11e6-9b81-3c997bcac048.png">

Have to refresh the page to get it work again.

I manage to get it working without errors properly by doing following changes, but I'm not familiar enough with the codebase to understand is there some other concequences with these changes:

``` js
        GoogleMapsLoader.load(function (_google) {
            google = _google;
            console.log('I just loaded google maps api');
            self._ready = true; // <---- ADDED THIS!
            self._initMapObject();
            self._update();

            //this._ready = google.maps.Map !== undefined;
            //if (!this._ready) L.Google.asyncWait.push(this);
        });
```

``` js

    _initMapObject: function () {
        if (!this._ready || !this._container) return; // <--- ADDED _container check!

        this._google_center = new google.maps.LatLng(0, 0);
        var map = new google.maps.Map(this._container, {
            center: this._google_center,

         // CODE CONTINUES....
```

Any help?

**Comment by Charmatzis** [comment]
Hi, I know this error but I didn't have time to find a solution to this, since my map was loaded successfully.  I will check out and I will release a new version when I will found a little bit time. If the above code works for now use it, I will come back as soon as possible.

**Comment by seanes** [comment]
I can confirm that OP's solution fixes the issue. Thank you, @ernoaapa for this walkthrough, and thank you, @Charmatzis for at great job on this very needed component.

**Comment by Charmatzis** [comment]
I have fixed this error, as @ernoaapa suggested.

THX, @ernoaapa
