### ISSUE TITLE
is it possible to make react-leaflet map supports  tilt view or something like google-native-maps pitchenable property

### ISSUE THREAD

**Issue by abtuhin** [Charmatzis/react-leaflet-google#13]

**Comment by Charmatzis** [comment]
Could you please, provide few examples and/or links?

**Comment by abtuhin** [comment]
https://osmbuildings.org/?lat=52.52111&lon=13.40988&zoom=16.4&rotation=0&tilt=30
Its an example of osmbuildings with 30 degreevangle with buildings. I just expect the map view would rotate on google map about 30 degree. 

https://github.com/airbnb/react-native-maps/blob/master/docs/mapview.md
 Here is a property called pitchenabled which is responsible for adjusting camera.
I am new in reactjs, will appreciate answer.

**Comment by Charmatzis** [comment]
Well the first link does it supported by the google maps api?
The second link it doesn't work with the react-leaflet with react-leaflet lib. (https://github.com/PaulLeCam/react-leaflet)

**Comment by abtuhin** [comment]
My first comment was to let you know the effect that i want; something like camera view adjust like 35 degree for maps web api.

https://developers.google.com/maps/documentation/android-api/views
I am using react-leaflet and react-leaflet-google layers. Now my concern is to implement the camera adjustment or tilt issue for web. 
http://leafletjs.com/examples/extending/extending-3-controls.html
Or, how can i make support for my react-leaflet component to have those tilt property.

Thanks...

**Comment by Charmatzis** [comment]
I am closing this issue, because it is obsolete.
