### ISSUE TITLE
Deprecated include of L.Mixin.Events: this property will be removed in future releases, please inherit from L.Evented instead. Error

### ISSUE THREAD

**Issue by s-chand** [Charmatzis/react-leaflet-google#16]
Hi,
Can we have this warning removed? I would think that this is a relatively easy fix. Happy to create a PR for it if you'd prefer that.

Great work here man! +1

> Deprecated include of L.Mixin.Events: this property will be removed in future releases, please inherit from L.Evented instead. Error

**Comment by Charmatzis** [comment]
Sure, feel free. I will be on a pull request mode this period, so keep on mind update your branch.
