### ISSUE TITLE
Resizing of parent container not handled

### ISSUE THREAD

**Issue by alexus37** [Charmatzis/react-leaflet-google#19]
Hi, thanks for the wrapper! I have used it till now nearly without any issues. However, after now I stumbled across a resizing problem. 

If I resize the map container it appears that the google tile layer is not resized and grey areas are visible. (see right end)
![error](https://user-images.githubusercontent.com/7422767/32720316-7fb1b7de-c863-11e7-9854-f797990eb0b3.png)

If I do the resizing with OSM everything works well.
![working](https://user-images.githubusercontent.com/7422767/32720384-b0b2d7b4-c863-11e7-97f7-5aa7073e8ccc.png)

FYI, I am calling the invalidateSize method of the map after the resize event.
```javascript
setTimeout(function () {
            if (this.map && this.map.leafletElement) { 
              console.log("updateMapSize started");
              this.map.leafletElement.invalidateSize(true); 
            }
          }.bind(this), 1000);
```

Also worth pointing out, is that this only happens in the roadmap mode, with the satellite mode it works perfect.

**Comment by alexus37** [comment]
After digging a bit deeper, I found out that on initalization in the onAdd function this._ready is undefined, thats why all listeners are not added.
```javascript
onAdd: function onAdd(map) {
	    L.GridLayer.prototype.onAdd.call(this, map);
	    this._initMutantContainer();

	    // this._GAPIPromise.then(function () {
	    if (this._ready) { // <========== is undefined 
	      this._map = map;

	      this._initMutant();

	      map.on('viewreset', this._reset, this);
	      map.on('move', this._update, this);
	      map.on('zoomend', this._handleZoomAnim, this);
	      map.on('resize', this._resize, this);

	      //20px instead of 1em to avoid a slight overlap with google's attribution
	      map._controlCorners.bottomright.style.marginBottom = '20px';

	      this._reset();
	      this._update();
	    }
	    //}.bind(this));
	  }
```

**Comment by Charmatzis** [comment]
@alexus37  do you have any updates from this issue?

**Comment by alexus37** [comment]
Yes it is still present, currently I am doing a little hack to get  a workaround. 
```javascript
componentDidMount() {
    // THIS IS A HACK TO FIX THE RESIZING PROBLEM
    // https://github.com/Charmatzis/react-leaflet-google/issues/19
    setTimeout(function () {
      this.setState({checkedLayer: ROADMAP});
    }.bind(this), 2000);
  }
```

This is basically first loading the SATELLITE view and than switching to the ROADMAP.
