### ISSUE TITLE
Support for react-leaflet 2.x

### ISSUE THREAD

**Issue by tmgordon3** [Charmatzis/react-leaflet-google#27]
React-Leaflet (https://react-leaflet.js.org/) is nearing version 2 release (currently RC1), and this is a request to update react-leaflet-google to support the upcoming release of react-leaflet v2.

**Comment by Charmatzis** [comment]
Thx, for the report.
Actions we be taken as soon as possible.

**Comment by danieldunderfelt** [comment]
I just submitted PR #29 that makes this plugin React-Leaflet 2 compatible.

**Comment by RustyRaptor** [comment]
Can we get this merged and pushed to npm asap?

**Comment by ashwinvandijk** [comment]
Agree with RustyRaptor. In the meantime you can load this package in your package.json like this:

`"react-leaflet-google": "https://github.com/danieldunderfelt/react-leaflet-google.git",`

**Comment by Charmatzis** [comment]
I have done the update.

Thx, guys for the support.
