### ISSUE TITLE
Make googlekey optional

### ISSUE THREAD

**Issue by Eschon** [Charmatzis/react-leaflet-google#3]
If you just want to use the google maps layer without any other functionality it works fine without an API key but `react-leaflet-google` shows an error because the googlekey is marked as required.

**Comment by Charmatzis** [comment]
I make it required because the google API key is nothing special to required it from Google, also is free...

**Comment by Eschon** [comment]
I know that it is free but it also is a little bit of wort to set up ;)
It's not a problem if you keep it required since it still works, but I thought I'd suggest making it optional since it still works without the key.
