### ISSUE TITLE
applying custom styles

### ISSUE THREAD

**Issue by tconroy** [Charmatzis/react-leaflet-google#5]
how would one apply custom styles to a google map using this plugin? A JSON object built with something like https://mapstyle.withgoogle.com/ ?

Thanks!

**Comment by Charmatzis** [comment]
You have to develop your own plugin, sorry!!!

**Comment by tconroy** [comment]
@Charmatzis hm.. So no interest in adding this feature? I'm not too familiar with Gmaps ( and not very familiar at all with react-leaflet, yet ) but it seems like we'd just need to pass `mapOptions.styles` through to setOptions? https://github.com/Charmatzis/react-leaflet-google/blob/master/src/leaflet.google.js#L33

**Comment by tconroy** [comment]
nevermind.... apparently the error existed between keyboard and chair ( aka, me :) )  passing a prop`mapOptions` with a styles key to the component does indeed work as expected! Closing this since I'm just a dummy. Thank you 👍
